main: com.pixesoj.deluxeteleport.DeluxeTeleport
website: https://wiki.pixesoj.com/deluxeteleport/
version: 2.5.4
name: DeluxeTeleport
api-version: 1.13
author: ["Pixesoj"]
softdepend: ["PlaceholderAPI", "Floodgate", "Vault", "LuckPerms"]