#====================================================================================#
#                          ___  ____   __    _    _  _  _                            #
#                        / __)(  _ \ /__\  ( \/\/ )( \( )                            #
#                        \__ \ )___//(__)\  )    (  )  (                             #
#                        (___/(__) (__)(__)(__/\__)(_)\_)                            #
#                                                                                    #
# This is the configuration file for the spawn's                                     #
#                                                                                    #
# You can consult the documentation for this section here:                           #
# https://wiki.pixesoj.com/deluxeteleport/characteristics/tpa/configuration          #
#                                                                                    #
# See the documentation for the time formats for these options:                      #
# https://wiki.pixesoj.com/deluxeteleport/time-formats                               #
#                                                                                    #
# If you would like any new features or need help let me know on my discord server:  #
# https://discord.com/invite/gcGarEbbbb                                              #
#====================================================================================#

# Sets whether /spawn, /delspawn and /setspawn will be enabled.
enabled: true

# By setting this to true, this function will be completely disabled as if it did not exist in the plugin.
# This is useful for when you have another plugin that takes care of this. If this is not the case, do not activate it.
# A reboot is required for it to take effect.
force_disable: false

# You can enable this if some other plugin interferes with the DeluxeTeleport command,
# and it will try to override any other commands.
high_priority: false

# Here you can add alias commands in addition to /spawn
# Restart your server after adding or removing an alias
commands_alias:
  spawn: []
  spawns:
    - spawnlist

# Add an alias to certain worlds to display in messages
aliases:
  world: "&aWorld"
  world_nether: "&cNether"
  world_the_end: "&dThe End"
  other_world: AnotherWorld

# If this is true you can put one spawn per world
by_world: false

# This is for when by_world is true and the /spawn command is used without specifying a spawn
teleport_in_by_world:
  # Will this function be enabled? If this is not true and by_world is true
  # then you will have to specify a spawn in the /spawn command
  enabled: false
  # Available options
  # General: Take to the general spawn (if there is one)
  # Specify: lead to a specific spawn
  spawn: General
  # If spawn is Specify then specify the name of the spawn here
  specify: world

# Teleport Delay Options
teleport_delay:
  # Enable teleport delay
  enabled: true
  # How long will the delay be in teleportation?
  time: 3s
  # Should teleport be canceled with movement?
  cancel_on_move: true

# Cooldown settings between each use of the /tpa command
cooldown:
  # Will it be enabled?
  enabled: true
  # Time between each use of the command
  time: 10m
  # Adjustments to cooldown by rank
  by_rank:
    # Will the cooldown be enabled by rank?
    enabled: true
    # Here you can set the time for each range, you can add as many as you want
    # Time is added in seconds
    ranks:
      # To assign permission in this example would be 'deluxeteleport.cooldown.rank.examplerank'
      vip: 5m
      staff: 1m 30s
    # Settings to assign permission automatically
    auto_ranks:
      # If this is enabled, and you have a compatible permissions plugin the cooldowns will be automatically assigned to users
      enabled: true
      # Permissions plugin to be used
      # Currently supported plugins are:
      # - LuckPerms
      permissions_plugin: LuckPerms
    # This indicates whether the longest or shortest time will be used in case of having more than 1 time for the same user.
    # Available options:
    # LONGEST
    # SHORTEST
    prioritize_time: SHORTEST
  # If this is true the data will be saved in each player's data file, this means that the data will not be lost when the server is shut down.
  save_playerdata: true

# Here you can set certain conditions before performing the teleportation and
# even execute actions when they are met or not. You can consult the documentation here:
# https://wiki.pixesoj.com/deluxeteleport/conditions
teleport_conditions:
  conditions:
    money:
      type: 'has money'
      amount: 500
      enabled: false
      deny_actions:
        insuficient:
          type: message
          message: "%prefix_spawn%&cYou don't have enough money, you need 500/%vault_money%"

# Here you can perform actions before, during, after and when canceling the delay,
# you can even add conditions to execute only in certain cases. You can consult the documentation here:
# https://wiki.pixesoj.com/deluxeteleport/actions
teleport_actions:
  default_messages: true
  actions:
    sound1:
      type: sound
      when: during_delay
      sound: ENTITY_EXPERIENCE_ORB_PICKUP
    actionbar1:
      type: actionbar
      when: during_delay
      message: "&aTeleporting in &b%spawn_delay_formatted%"
    sound2:
      type: sound
      when: cancel_delay
      sound: BLOCK_ANVIL_LAND
    actionbar2:
      type: actionbar
      when: cancel_delay
      message: "&cTeleportation cancelled"
      duration: 3
    sound3:
      type: sound
      when: after_delay, none
      sound: ENTITY_PLAYER_LEVELUP
    actionbar3:
      type: actionbar
      when: after_delay, none
      message: "&aTeleported"
      duration: 2