#====================================================================================#
#                                 ____  ____   __                                    #
#                                (_  _)(  _ \ /__\                                   #
#                                  )(   )___//(__)\                                  #
#                                 (__) (__) (__)(__)                                 #
#                                                                                    #
# This is the configuration file for the tpa                                         #
#                                                                                    #
# You can consult the documentation for this section here:                           #
# https://pixesoj-dev.gitbook.io/plugins/deluxeteleport/characteristics/tpa          #
#                                                                                    #
# See the documentation for the time formats for these options:                      #
# https://wiki.pixesoj.com/deluxeteleport/time-formats                               #
#                                                                                    #
# If you would like any new features or need help let me know on my discord server:  #
# https://discord.com/invite/gcGarEbbbb                                              #
#====================================================================================#

# Sets whether /tpa, /tpacancel, /tpaccept, /tpahere and /tpatoggle will be enabled.
enabled: true

# By setting this to true, this function will be completely disabled as if it did not exist in the plugin.
# This is useful for when you have another plugin that takes care of this. If this is not the case, do not activate it.
# A reboot is required for it to take effect.
force_disable: false

# You can enable this if some other plugin interferes with the DeluxeTeleport command,
# and it will try to override any other commands.
high_priority: false

# Here you can add alias commands in addition to the original ones
# Restart your server after adding or removing an alias
commands_alias:
  tpa:
    - tprequest
  tpaccept: []
  tpacancel: []
  tpadeny: []
  tpahere: []
  tpatoggle: []

# Indicates whether to autofill online player names in the tab
autocomplete_names: true

# This will indicate if by default the player will have teleport requests enabled (this changes after using /tpatoggle)
status_default: true

# If a player is not specified in the /tpaccept, /tpahere, tpadeny and /tpacancel commands, which player will be taken into account
# Available options:
# First: select the first player who sent a teleport request
# Last: select the last player who sent a teleport request
# None: this means that a player must necessarily be specified
list_position: Last

# Settings for when the /tpa command is used
send:
  # If this is activated, players will be able to send themselves (I do not recommend it)
  tpa_himself: false
  # If this is active, it will not be taken into account if the player has tpa requests disabled
  ignore_tpa_status: false
  # If this is enabled, players may receive more than one teleport request.
  multiple_tpa: true

# Settings for when a player receives a teleport request
request:
  # If this is active, a clickable message will be sent to the player to accept or reject
  click_tpa: true
  # This will attempt to focus the teleport request message.
  centered_message: true

# Here you can configure whether the teleport requests and the time will expire.
expiration:
  # Will it be enabled?
  enabled: true
  # How long will it take to expire (in seconds)
  time: 3m

# Teleport delay settings (This only applies to the player who will be teleported)
delay:
  # Will the delay be enabled?
  enabled: true
  # Time between acceptance and teleportation
  time: 3s
  # Should teleport be canceled with movement?
  cancel_on_move: true

# Cooldown settings between each use of the /tpa command
# Restart the server if the counter reaches 0 and nothing happens from there
cooldown:
  # Will it be enabled?
  enabled: true
  # Time between each use of the command
  time: 10m
  # This causes the cooldown to be used until the teleport is accepted.
  count_when_teleporting: true
  # Choose which player the cooldown will be added to.
  # Available options:
  # Player: The player to be teleported to
  # TargetPlayer: The player who will be teleported
  # Both: Both players
  coldown_for: TargetPlayer
  # Adjustments to cooldown by rank
  by_rank:
    # Will the cooldown be enabled by rank?
    enabled: true
    # Settings when send.multiple_tpa is enabled
    in_multiple:
      # If this is false it means that if the player is on cooldown and has pending requests then they cannot be accepted.
      accept_pending: false
    # Here you can set the time for each range, you can add as many as you want
    # Time is added in seconds
    ranks:
      # To assign permission in this example would be 'deluxeteleport.cooldown.rank.examplerank'
      vip: 5m
      staff: 1m 30s
    # Settings to assign permission automatically
    auto_ranks:
      # If this is enabled, and you have a compatible permissions plugin the cooldowns will be automatically assigned to users
      enabled: true
      # Permissions plugin to be used
      # Currently supported plugins are:
      # - LuckPerms
      permissions_plugin: LuckPerms
    # This indicates whether the longest or shortest time will be used in case of having more than 1 time for the same user.
    # Available options:
    # LONGEST
    # SHORTEST
    prioritize_time: SHORTEST
  # If this is true the data will be saved in each player's data file, this means that the data will not be lost when the server is shut down.
  save_playerdata: true

# Support for bedrock edition, you must have Floodgate and Geyser installed
bedrock_support:
  # You can activate this option if you use Geyser
  enabled: false
  # Since clickable messages are not supported in bedrock edition, this function will prevent the buttons from being sent.
  click_tpa: false
  # If this is active then a different message will be sent when they receive a teleport request
  different_message: true


# Here you can set certain conditions before performing the teleportation and
# even execute actions when they are met or not. You can consult the documentation here:
# https://wiki.pixesoj.com/deluxeteleport/conditions
# Important: Conditions apply to the player who sends the request.
teleport_conditions:
  conditions:
    exp:
      type: 'has exp'
      amount: 10
      level: true
      enabled: false
      deny_actions:
        actions:
          insuficient:
            type: message
            message: '%prefix_spawn%&cYou do not have the necessary EXP levels &8(10&8)'

# Here you can perform actions before, during, after and when canceling the delay,
# you can even add conditions to execute only in certain cases. You can consult the documentation here:
# https://wiki.pixesoj.com/deluxeteleport/actions
# Important: Actions apply to the player who sends the request
teleport_actions:
  default_messages: true
  actions:
    sound:
      type: sound
      when: after_delay
      whom: both
      sound: ENTITY_ENDERMAN_TELEPORT
      volume: 0.8
      pitch: 1